// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMART.Web.Models;

public partial class Comunicado
{
    public int Coid { get; set; }

    public string Coassunto { get; set; }

    public string Cotitulo { get; set; }

    public string Codata { get; set; }
}