// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SMART.Web.Models;

public partial class Endereco
{
    public int Enid { get; set; }

    public string Enlogradouro { get; set; }

    public string Ennumero { get; set; }

    public string Encomplemento { get; set; }

    public string Enbairro { get; set; }

    public string Encidade { get; set; }

    public string Enestado { get; set; }

    public string Encep { get; set; }

    public int? Enidusuario { get; set; }

    public virtual Usuario EnidusuarioNavigation { get; set; }
}