// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SMART.Web.Models;

public partial class SMARTNContext : DbContext
{
    public SMARTNContext()
    {
    }

    public SMARTNContext(DbContextOptions<SMARTNContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Comunicado> Comunicados { get; set; }

    public virtual DbSet<Endereco> Enderecos { get; set; }

    public virtual DbSet<Usuario> Usuarios { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsbuilder)
=> optionsbuilder.UseSqlServer("data source=localhost\\SQLEXPRESS;Initial Catalog=SMARTN;Integrated Security=True; TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Comunicado>(entity =>
        {
            entity.HasKey(e => e.Coid);

            entity.Property(e => e.Coid).HasColumnName("COid");
            entity.Property(e => e.Coassunto)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("COassunto");
            entity.Property(e => e.Codata)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("COdata");
            entity.Property(e => e.Cotitulo)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("COtitulo");
        });

        modelBuilder.Entity<Endereco>(entity =>
        {
            entity.HasKey(e => e.Enid);

            entity.ToTable("Endereco");

            entity.Property(e => e.Enid).HasColumnName("ENid");
            entity.Property(e => e.Enbairro)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ENbairro");
            entity.Property(e => e.Encep)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ENcep");
            entity.Property(e => e.Encidade)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ENcidade");
            entity.Property(e => e.Encomplemento)
                .IsUnicode(false)
                .HasColumnName("ENcomplemento");
            entity.Property(e => e.Enestado)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ENestado");
            entity.Property(e => e.Enidusuario).HasColumnName("ENidusuario");
            entity.Property(e => e.Enlogradouro)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ENlogradouro");
            entity.Property(e => e.Ennumero)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("ENnumero");

            entity.HasOne(d => d.EnidusuarioNavigation).WithMany(p => p.Enderecos)
                .HasForeignKey(d => d.Enidusuario)
                .HasConstraintName("FK_Endereco_Usuarios");
        });

        modelBuilder.Entity<Usuario>(entity =>
        {
            entity.HasKey(e => e.Usid);

            entity.Property(e => e.Usid).HasColumnName("USid");
            entity.Property(e => e.Usdatanascimento)
                .HasColumnType("datetime")
                .HasColumnName("USdatanascimento");
            entity.Property(e => e.Usdataregistro)
                .HasColumnType("datetime")
                .HasColumnName("USdataregistro");
            entity.Property(e => e.Usemail)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("USemail");
            entity.Property(e => e.Usnome)
                .IsUnicode(false)
                .HasColumnName("USnome");
            entity.Property(e => e.Ussenha)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("USsenha");
            entity.Property(e => e.Ustelefone)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("UStelefone");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}