// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace SMART.Web.Models;

public partial class Usuario
{
    public int Usid { get; set; }

    [Display(Name ="Nome")]
    public string Usnome { get; set; }

    public string Usemail { get; set; }

    public string Ussenha { get; set; }

    public string Ustelefone { get; set; }

    public DateTime? Usdatanascimento { get; set; }

    public DateTime? Usdataregistro { get; set; }

    public virtual ICollection<Endereco> Enderecos { get; set; } = new List<Endereco>();
}